[package]
name = "multiple-select"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2021"
license = "MIT"

[dependencies]
zellij-tile = { path = "../../zellij-tile" }
fuzzy-matcher = "0.3.7"
