version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Only add packages very sporadically here for now.
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      # Allow only direct updates
      - dependency-name: "log"
  - package-ecosystem: "cargo"
    directory: "/zellij-utils/"
    schedule:
      interval: "monthly"
    allow:
      # Allow only direct updates
      - dependency-name: "log"
      - dependency-name: "log4rs"
      - dependency-name: "clap"
      - dependency-name: "clap_complete"


